version: '3.9'
services:
  demo-postgres:
    image: 'postgres'
    container_name: demo-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=docker-k8s-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
