version: "3.5"

services:

  zookeeper:
    extends:
      file: kafka/docker-compose.yaml
      service: zookeeper
    ports:
      - "2181:2181"

  kafka:
    extends:
      file: kafka/docker-compose.yaml
      service: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  kafka-ui:
    extends:
      file: kafka/docker-compose.yaml
      service: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8082:8080"

  dapr-placement:
    extends:
      file: dapr/docker-compose.yaml
      service: dapr-placement
    depends_on:
      - kafka

  demo-back:
    extends:
      file: dapr/docker-compose.yaml
      service: demo-back
    depends_on:
      - dapr-placement
    ports:
      - "8081:8080"
      - "3501:3500"

  demo-back-sidecar:
    extends:
      file: dapr/docker-compose.yaml
      service: demo-back-sidecar
    depends_on:
      - demo-back
    network_mode: "service:demo-back"

  demo-front:
    extends:
      file: dapr/docker-compose.yaml
      service: demo-front
    depends_on:
      - dapr-placement
    ports:
      - "4200:80"

  demo-postgres:
    extends:
      file: dapr/docker-compose.yaml
      service: demo-postgres
    depends_on:
      - dapr-placement
    ports:
      - "5431:5432"

volumes:
    data:
        driver: local
        
networks:
  default:
    external:
      name: dapr-env
