---
apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-demo-backend-svc
spec:
  type: NodePort
  selector:
    app: docker-k8s-demo
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
