---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: docker-k8s-demo
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: docker-k8s-demo
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend-demo
          image: "fsouayah/demo-backend:latest"
          ports:
            - name: http
              containerPort: 8080