version: '3.9'
services:
  demo-postgres:
    image: 'postgres'
    container_name: demo-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=docker-k8s-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  demo-back:
    build: ../../docker-k8s-back
    container_name: demo-back
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=demo-postgres
    depends_on:
      - demo-postgres
  demo-front:
    build: 
      context: ../../docker-k8s-front
      dockerfile: Dockerfile-dev
    container_name: demo-front
    ports:
      - 4200:80
    depends_on:
      - demo-back